services:
  auth:
    deploy:
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.auth-app1.entrypoints: https
        traefik.http.routers.auth-app1.rule: Host(`auth-app1-nhost.carlosrobertodevops.com.br`)
        traefik.http.routers.auth-app1.tls.certresolver: letsencrypt
        traefik.http.services.auth-app1.loadbalancer.server.port: "4000"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      AUTH_ACCESS_CONTROL_ALLOWED_EMAIL_DOMAINS: ""
      AUTH_ACCESS_CONTROL_ALLOWED_EMAILS: ""
      AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS: ""
      AUTH_ACCESS_CONTROL_BLOCKED_EMAIL_DOMAINS: ""
      AUTH_ACCESS_CONTROL_BLOCKED_EMAILS: ""
      AUTH_ACCESS_TOKEN_EXPIRES_IN: "900"
      AUTH_ANONYMOUS_USERS_ENABLED: "false"
      AUTH_API_PREFIX: /v1
      AUTH_CLIENT_URL: https://your-client-domain.com
      AUTH_CONCEAL_ERRORS: "false"
      AUTH_DISABLE_NEW_USERS: "false"
      AUTH_DISABLE_SIGNUP: "false"
      AUTH_EMAIL_PASSWORDLESS_ENABLED: "false"
      AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED: "false"
      AUTH_GRAVATAR_DEFAULT: blank
      AUTH_GRAVATAR_ENABLED: "true"
      AUTH_GRAVATAR_RATING: g
      AUTH_HOST: 0.0.0.0
      AUTH_JWT_CUSTOM_CLAIMS: '{}'
      AUTH_LOCALE_ALLOWED_LOCALES: en
      AUTH_LOCALE_DEFAULT: en
      AUTH_MFA_ENABLED: "false"
      AUTH_MFA_TOTP_ISSUER: ""
      AUTH_PASSWORD_HIBP_ENABLED: "false"
      AUTH_PASSWORD_MIN_LENGTH: "9"
      AUTH_PORT: "4000"
      AUTH_RATE_LIMIT_ENABLE: "true"
      AUTH_REFRESH_TOKEN_EXPIRES_IN: "2592000"
      AUTH_SERVER_URL: https://auth-app1-nhost.carlosrobertodevops.com.br/v1
      AUTH_SMTP_AUTH_METHOD: PLAIN
      AUTH_SMTP_HOST: smtp.your-smtp-host.com
      AUTH_SMTP_PASS: your-smtp-password
      AUTH_SMTP_PORT: "587"
      AUTH_SMTP_SECURE: "true"
      AUTH_SMTP_SENDER: noreply@your-domain.com
      AUTH_SMTP_USER: your-smtp-user
      AUTH_USER_DEFAULT_ALLOWED_ROLES: user,me
      AUTH_USER_DEFAULT_ROLE: user
      HASURA_GRAPHQL_ADMIN_SECRET: E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret_password@pgbouncer:6432/app1
      HASURA_GRAPHQL_GRAPHQL_URL: https://hasura-app1-nhost.carlosrobertodevops.com.br/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: '{"key":"E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp","type":"HS256"}'
      POSTGRES_MIGRATIONS_CONNECTION: postgres://postgres:secret_password@pgbouncer:6432/app1
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -S
        - http://localhost:4000/healthz
      timeout: 1m0s
      interval: 5s
      start_period: 1m0s
    image: nhost/hasura-auth:0.33.0
    networks:
      traefik-public: null
    volumes:
      - type: bind
        source: ./emails
        target: /app/email-templates
  backup:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      BACKUP_KEEP_DAYS: "14"
      POSTGRES_DATABASE: app1
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres
      S3_ACCESS_KEY_ID: M2hNHOMDXacHJXJAvTJP
      S3_BUCKET: nhost
      S3_ENDPOINT: https://minio-api.mondaha.com/
      S3_PREFIX: app1_backup
      S3_REGION: us-east-1
      S3_SECRET_ACCESS_KEY: peePBcA8BRYW8A6gW5V46gpX2nSJAYxErl78M2VU
      SCHEDULE: '@daily'
    image: eeshugerman/postgres-backup-s3:16
    networks:
      postgres_network: null
  dashboard:
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.auth-dashboard-app1.basicauth.users: user:$$apr1$$ldguuY/O$$MVR30H5//NIte8c1ezkfkf
        traefik.http.routers.dashboard-app1.entrypoints: https
        traefik.http.routers.dashboard-app1.middlewares: auth-dashboard-app1
        traefik.http.routers.dashboard-app1.rule: Host(`dashboard-app1-nhost.carlosrobertodevops.com.br`)
        traefik.http.routers.dashboard-app1.tls.certresolver: letsencrypt
        traefik.http.services.dashboard-app1.loadbalancer.server.port: "3000"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      NEXT_PUBLIC_ENV: prod
      NEXT_PUBLIC_NHOST_ADMIN_SECRET: E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp
      NEXT_PUBLIC_NHOST_AUTH_URL: https://auth-app1-nhost.carlosrobertodevops.com.br/v1
      NEXT_PUBLIC_NHOST_CONFIGSERVER_URL: ""
      NEXT_PUBLIC_NHOST_FUNCTIONS_URL: ""
      NEXT_PUBLIC_NHOST_GRAPHQL_URL: https://hasura-app1-nhost.carlosrobertodevops.com.br/v1/graphql
      NEXT_PUBLIC_NHOST_HASURA_API_URL: ""
      NEXT_PUBLIC_NHOST_HASURA_CONSOLE_URL: ""
      NEXT_PUBLIC_NHOST_HASURA_MIGRATIONS_API_URL: ""
      NEXT_PUBLIC_NHOST_PLATFORM: "false"
      NEXT_PUBLIC_NHOST_STORAGE_URL: https://storage-app1-nhost.mycarlosrobertodevops.com.br/v1
    image: nhost/dashboard:1.27.0
    networks:
      traefik-public: null
  graphql-engine:
    deploy:
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.hasura-app1.entrypoints: https
        traefik.http.routers.hasura-app1.rule: Host(`hasura-app1-nhost.carlosrobertodevops.com.br`)
        traefik.http.routers.hasura-app1.tls.certresolver: letsencrypt
        traefik.http.services.hasura-app1.loadbalancer.server.port: "8080"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret_password@postgres:5432/app1
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"key":"E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp","type":"HS256"}'
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:secret_password@postgres:5432/app1
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      NHOST_WEBHOOK_SECRET: YXuDagH9eyL5SvjL3EPGUz7k54iRAU27
    image: hasura/graphql-engine:v2.42.0
    networks:
      postgres_network: null
      traefik-public: null
  storage:
    command:
      - serve
    deploy:
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.storage-app1.entrypoints: https
        traefik.http.routers.storage-app1.rule: Host(`storage-app1-nhost.mycarlosrobertodevops.com.br`)
        traefik.http.routers.storage-app1.tls.certresolver: letsencrypt
        traefik.http.services.storage-app1.loadbalancer.server.port: "5000"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      BIND: :5000
      HASURA_ENDPOINT: https://hasura-app1-nhost.carlosrobertodevops.com.br/v1
      HASURA_GRAPHQL_ADMIN_SECRET: E0NEn8SXkmRI7iuEceHBU8VEpOCeFlFuwCT1pfTlfWiTgcfk2hH6RlhffGi7k2Cp
      HASURA_METADATA: "1"
      PORT: "5000"
      POSTGRES_MIGRATIONS: "1"
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:secret_password@pgbouncer:6432/app1?sslmode=disable
      PUBLIC_URL: https://storage-app1-nhost.mycarlosrobertodevops.com.br
      S3_ACCESS_KEY: M2hNHOMDXacHJXJAvTJP
      S3_BUCKET: nhost
      S3_ENDPOINT: https://minio-api.mondaha.com/
      S3_REGION: us-east-1
      S3_ROOT_FOLDER: ""
      S3_SECRET_KEY: peePBcA8BRYW8A6gW5V46gpX2nSJAYxErl78M2VU
    image: nhost/hasura-storage:0.6.1
    networks:
      traefik-public: null
networks:
  postgres_network:
    name: postgres-stack_postgres_network
    external: true
  traefik-public:
    name: traefik-public
    external: true
