# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'nhost-project'

scrape_configs:
  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - host: tcp://docker-socket-proxy:2375
        role: tasks
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: .*cadvisor
        action: keep

  - job_name: 'node-exporter'
    dockerswarm_sd_configs:
      - host: tcp://docker-socket-proxy:2375
        role: tasks
        port: 9100
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: .*node-exporter
        action: keep

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
  
  #- job_name: 'pgcat'
  #  static_configs:
  #    - targets: ['pgcat:9930']
  #  scrape_interval: 120s # By default, scrape targets every 15 seconds.
    
  
  #- job_name: 'postgres'
  #  static_configs:
  #    - targets: ['postgres-exporter:9187']
  #  scrape_interval:     120s # By default, scrape targets every 15 seconds.
