server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_COMPOSE_PROJECT]
        target_label: compose_project
      - source_labels: [__meta_docker_container_label_COMPOSE_SERVICE]
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_app_name]
        target_label: app_name
      - source_labels: [__meta_docker_container_label_environment]
        target_label: environment
      - source_labels: [__meta_docker_container_name]
        regex: '/(?P<container_name>.+)'
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        regex: '([^\.]+)\..*'
        target_label: service_name
